bcnrun/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('club.urls'), name='club_urls'),
    path('accounts/', include('allauth.urls')),
]

club/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path('events/', views.EventList.as_view(), name='events'),
    path('', views.HomePage.as_view(), name='home'),
    path('contact/', views.contact, name='contact'),
    path('booking/', views.booking, name='booking'),
    path('manage/', views.ManageBooking.as_view(), name='manage'),
    path('edit-booking/<int:id>/', views.EditBooking.as_view(), name='edit_booking'),
    path('delete_booking/<int:id>/', views.delete_booking, name='delete_booking'),
]

club/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField

DAYS = ((0, "Tuesday"), (1, "Thursday"), (2, "Saturday"))
LEVELS = ((0, "Beginner"), (1, "Intermediate"), (2, "Push yourself"))


# schema for Event model
class Event(models.Model):
    name = models.CharField(max_length=200, unique=True)
    day = models.IntegerField(choices=DAYS)
    level = models.IntegerField(choices=LEVELS)
    location = models.CharField(max_length=200)
    featured_image = CloudinaryField('image', default='placeholder')

    def __str__(self):
        return self.name


# schema for Booking model
class Booking(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField(unique=False)
    date = models.DateField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} - {self.email} booked on {self.date}"


# schema for Contact model of contact form
class Contact(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField(unique=False)
    message = models.TextField(blank=False)

    def __str__(self):
        return f"{self.message} from {self.email}"

club/forms.py
from .models import Contact, Booking
from django import forms


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('name', 'email', 'message',)


class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = ('name', 'email', 'date',)

    date = forms.DateField(
            widget=forms.TextInput(
                attrs={'type': 'date'}
            )
        )

club/views.py
from django.shortcuts import render, reverse, get_object_or_404
from django.views import generic, View
from django.http.response import HttpResponseRedirect
from django.views.generic.base import TemplateView
from django.contrib import messages
from .models import Event, Booking, DAYS, LEVELS
from .forms import ContactForm, BookingForm


class HomePage(TemplateView):
    # view to render the homepage
    template_name = 'index.html'


# get string values from tuples
def get_day_from_dayint(dayint):
    for day_tuple in DAYS:
        if day_tuple[0] == dayint:
            return day_tuple[1]


def get_level_from_levelint(levelint):
    for level_tuple in LEVELS:
        if level_tuple[0] == levelint:
            return level_tuple[1]


class EventList(generic.ListView):
    # view to render the Event objects
    model = Event
    template_name = 'events.html'

    def get_queryset(self):
        events = Event.objects.all()
        for event in events:
            event.day_string = get_day_from_dayint(event.day)
            event.level_string = get_level_from_levelint(event.level)

        return events


def contact(request):
    # view to render the Contact form to contact.html
    contact_form = None
    if request.method == 'POST':
        contact_form = ContactForm(data=request.POST)
        if contact_form.is_valid():
            contact_form.save()
            messages.add_message(request, messages.SUCCESS, 'Message sent!')
            return HttpResponseRedirect(reverse('contact'))
    else:
        contact_form = ContactForm()

    context = {'contact_form': contact_form}

    return render(request, 'contact.html', context)


def booking(request):
    # view to render the Booking form to booking.html
    booking_form = None

    if request.method == 'POST':
        booking_form = BookingForm(data=request.POST)
        if booking_form.is_valid():
            booked_run = Booking.objects.create(
                user=request.user,
                name=request.POST.get("name", ""),
                email=request.POST.get("email", ""),
                date=request.POST.get("date", "")
            )
            booked_run.save()
            messages.add_message(request, messages.SUCCESS, 'Run booked!')
            return HttpResponseRedirect(reverse('booking'))
    else:
        booking_form = BookingForm()

    context = {'booking_form': booking_form}

    return render(request, 'booking.html', context)


class ManageBooking(generic.ListView):
    # view to render the manage booking page for logged in user
    model = Booking
    context_object_name = 'runs'
    template_name = 'manage.html'

    def get_queryset(self):
        return Booking.objects.filter(user=self.request.user)


class EditBooking(View):
    # view to render the edit booking form for logged in user
    def get(self, request, id):
        queryset = Booking.objects.filter(user=request.user)
        run = get_object_or_404(queryset, id=id)
        context = {'edit_booking_form': BookingForm(instance=run)}
        return render(request, 'edit-booking.html', context)

    def post(self, request, id):
        queryset = Booking.objects.filter(user=request.user)
        run = get_object_or_404(queryset, id=id)
        edit_booking_form = BookingForm(request.POST, instance=run)
        context = {'edit_booking_form': BookingForm(instance=run)}

        if edit_booking_form.is_valid():
            edit_booking_form.save()
            messages.add_message(request, messages.SUCCESS,
                                 'Booking successfully edited')
            return HttpResponseRedirect(reverse('manage'))

        return render(request, 'edit-booking.html', context)


def delete_booking(request, id):
    # view to delete a specific booking for logged in user
    queryset = Booking.objects.filter(user=request.user)
    run = get_object_or_404(queryset, id=id)

    run.delete()
    messages.add_message(request, messages.SUCCESS, 'Booking cancelled')
    return HttpResponseRedirect(reverse('manage'))

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Fun running group based in Barcelona. Three runs per week." />
    <meta name="keywords" content="run, running, fitness, keep fit, BCN RUN, Barcelona" />
    <meta name="author" content="Ellie Thurlwell" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <!-- bootstrap theme stylesheet -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/freelancer.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="shortcut icon" href="{% static 'assets/icon.png' %}" type="image/x-icon">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
    <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
    <script src="{% static 'js/script.js' %}"></script>
    <title>BCN RUN</title>
</head>
<body>
    <!-- navigation - mobile view responsive -->
    <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}">BCN RUN</a>
            <button class="navbar-toggler text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'events' %}">Events</a></li>
                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'contact' %}">Contact</a></li>
                    {% if user.is_authenticated %}
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'booking' %}">Book</a></li>
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'manage' %}">Manage</a></li>
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'account_logout' %}">Log Out</a></li>
                    {% else %}
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'account_signup' %}">Join Us</a></li>
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'account_login' %}">Log In</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <!-- user feedback messages -->
    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" id="msg" role="alert">
                    {{ message | safe }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <!-- main content -->
    <main>
        {% block content %}
        <!-- page content goes here -->
        {% endblock content %}
    </main>

    <!-- footer socials -->
    <footer class="footer text-center">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-4 mb-lg-0">
                    <h4 class="text-uppercase mb-4">Follow Us!</h4>
                    <a class="btn btn-outline-light btn-social mx-1" href="http://facebook.com" target="_blank" rel="noopener" aria-label="Find us on Facebook (opens in a new tab)"><i class="fab fa-fw fa-facebook-f"></i></a>
                    <a class="btn btn-outline-light btn-social mx-1" href="http://twitter.com" target="_blank" rel="noopener" aria-label="Find us on Twitter (opens in a new tab)"><i class="fab fa-fw fa-twitter"></i></a>
                    <a class="btn btn-outline-light btn-social mx-1" href="http://instagram.com" target="_blank" rel="noopener" aria-label="Find us on Instagram (opens in a new tab)"><i class="fab fa-instagram"></i></a>
                    <a class="btn btn-outline-light btn-social mx-1" href="http://strava.com" target="_blank" rel="noopener" aria-label="Find us on Strava (opens in a new tab)"><i class="fab fa-strava"></i></a>
                </div>
            </div>
        </div>
    </footer>

    <!-- google maps api -->
    <script src="https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/markerclusterer.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDwgv4M4kyqoWPb7s3j1NOkBlScKA0MvF4&callback=initMap" async></script>
    <!-- bootstrap theme script -->
    <script src="{% static 'js/freelancerscript.js' %}"></script>
    <!-- message timeout -->
    <script>
        setTimeout(function () {
            let messages = document.getElementById('msg');
            let alert = new bootstrap.Alert(messages);
            alert.close();
        }, 1500);
    </script>
</body>
</html>

templates/booking.html
{% extends 'base.html' %}

{% block content %}

{% load crispy_forms_tags %}

<section class="page-section">
    <div class="container">
        <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0 page-title">
        Book a run
        </h2>

        {% if user.is_authenticated %}
        <!-- display form content to book a run -->
            <div class="row justify-content-center">
                <div class="col-lg-8">
                    <p>Join us for a run!</p>
                    <p>Remember, we do a different run on each of our days:</p>
                    <ul>
                        <li><strong>Tuesday = beginner</strong></li>
                        <li><strong>Thursday = push yourself</strong></li>
                        <li><strong>Saturday = intermediate</strong></li>
                    </ul>
                    <form method="POST" style="margin-top: 1.3em;">
                        {{ booking_form | crispy }}
                        {% csrf_token %}
                        <button type="submit" class="col-sm-2 btn btn-primary btn-input">Book run</button>
                    </form>
                </div>
            </div>
        {% else %}
        <!-- prompt to sign up or login, with links -->
            <div class="row justify-content-center">
                <div class="col-lg-8">
                    <p>To join us on one of our runs you need to be a member.</p>
                    <p>Please either <a href="{% url 'account_login' %}">log in</a> to your account</p>
                    <p>or <a href="{% url 'account_signup' %}">become a member</a> to book a run</p>
                </div>
            </div>
        {% endif %}
    </div>
</section>


{% endblock %}

templates/contact.html
{% extends 'base.html' %}

{% block content %}

{% load crispy_forms_tags %}

<section class="page-section">
    <div class="container">
        <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0 page-title">
        Contact Us
        </h2>
        <!-- display contact form -->
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <p>Want to get in touch? Fill out the form and we'll get back to you as soon as we finish our run!</p>
                    
                <form method="POST" style="margin-top: 1.3em;">
                    {{ contact_form | crispy }}
                    {% csrf_token %}
                    <button type="submit" class="col-sm-2 btn btn-primary btn-input">Send message</button>
                </form>
            </div>
        </div>
    </div>
</section>

{% endblock %}

templates/edit-booking.html
{% extends 'base.html' %}

{% block content %}

{% load crispy_forms_tags %}

<section class="page-section">
    <div class="container">
        <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0 page-title">
        Edit your run
        </h2>

        {% if user.is_authenticated %}
        <!-- display form content to alter a run -->
            <div class="row justify-content-center">
                <div class="col-lg-8">
                    <p>Edit you run with us!</p>
                    <p>Remember, we do a different run on each of our days:</p>
                    <ul>
                        <strong>
                            <li>Tuesday = beginner</li>
                            <li>Thursday = push yourself</li>
                            <li>Saturday = intermediate</li>
                        </strong>
                    </ul>
                    <form method="POST" style="margin-top: 1.3em;">
                        {{ edit_booking_form | crispy }}
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary btn-input">Confirm edit</button>
                    </form>
                </div>
            </div>
        {% else %}
            <!-- prompt to sign up or login, with links -->
            <div class="row justify-content-center">
                <div class="col-lg-8">
                    <p>To join us on one of our runs you need to be a member.</p>
                    <p>Please either <a href="{% url 'account_login' %}">log in</a> to your account</p>
                    <p>or <a href="{% url 'account_signup' %}">become a member</a> to book a run</p>
                </div>
            </div>
        {% endif %}
    </div>
</section>


{% endblock %}

templates/events.html
{% extends 'base.html' %}

{% block content %}
<section class="page-section">
    <div class="container">
        <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0 page-title">
        Events
        </h2>
        <div class="row justify-content-center">
            <div class="col-sm-6">
                <div id="map"></div>
            </div>
        </div>
        <div class="row justify-content-center">
        <!-- event items from model-->
            {% for event in event_list %}
                <div class="col-sm-6 event-card">
                    <div class="card">
                        {% if "placeholder" in event.featured_image.url %}
                            <img src="https://res.cloudinary.com/elliecloud94/image/upload/v1640370315/hero_ldzbyr.jpg" class="card-img-top" alt="{{ event.location }}">
                        {% else %}
                            <img src="{{ event.featured_image.url }}" class="card-img-top" alt="{{ event.location }}">
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">{{ event.name }}</h5>
                            <p class="card-text">Join us on {{ event.day_string }} for a run at {{ event.location }}.</p><p>The level today is: {{ event.level_string }}.</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="row justify-content-center">
            <a class="col-sm-2 btn btn-primary btn-input" id="btn-book" href="{% url 'booking' %}">Book now!</a>
        </div>
    </div>
</section>


{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block content %}
<div id="index">
    <!-- header -->
    <header class="masthead bg-primary text-white text-center" id="header">
        <div class="container d-flex align-items-center flex-column" id="headerdiv">
        <!-- Masthead Avatar Image-->
            <img src="https://res.cloudinary.com/elliecloud94/image/upload/v1640528877/hero_rfxb1n.jpg" alt="bcn run header" id="heroimg"/>
            <h1 class="masthead-heading text-uppercase mb-0" id="title">BCN RUN</h1>
            <div class="divider-custom divider-light">
                <div class="divider-custom-line headerdiv"></div>
                <div class="headerdiv"><i class="fas fa-running"></i></div>
                <div class="divider-custom-line"></div>
            </div>
            <p class="masthead-subheading font-weight-light mb-0">fun and friendly running club in beautiful Barcelona</p>
        </div>
    </header>
    <!-- about section -->
    <div class="container">
        <h2 class="page-section-heading text-center text-uppercase text-secondary" id="about">
        About
        </h2>
        <div class="row justify-content-center" id="about-text">
            <div class="col-lg-8">
                <p class="lead">
                    BCN RUN is a running group focused on people. A friendly, fun and sometimes fast group, we run TOGETHER. We believe that what's most important is enjoying yourself when you run. PBs are nice, but not the be all and end all. However, as we are an inclusive club, there's definitly a place for you if you do want to chase that next record!
                </p>
                <p>
                    We meet three times a week in different locations in Barcelona. Each day is a different level run: Beginner for those starting out or who want an easy pace run, Intermediate for those looking to increase distance and/or speed, and Push Yourself for those who want to give it their all on a tougher course. Check out the Events page to see the locations and days!
                </p>
                <p class="lead">
                    We hope to see you at a BCN RUN event soon!
                </p>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/manage.html
{% extends 'base.html' %}

{% block content %}

<!-- user area to manage bookings -->
<section class="page-section">
    <div class="container">
        <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0 page-title">
        Your bookings
        </h2>
        <div class="row justify-content-center">
            {% for run in runs %}
                <div class="col-sm-4 manage-card">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card_title">Your run</h5>
                            <p class="card_text">{{ run.user }}, you are booked for a run on {{ run.date }}</p>
                            <span><a class="col-sm-3 btn btn-primary btn-manage" href="{% url 'edit_booking' run.id %}">Edit</a></span>
                            <span><a class="col-sm-3 btn btn-primary btn-manage" href="{% url 'delete_booking' run.id %}">Cancel</a></span>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</section>

{% endblock %}